### ISSUE TITLE
Kitchen Vcenter Converge Issue

### ISSUE THREAD

**Issue by tas50** [chef/kitchen-vcenter#143]
We are seeing this when trying to get a test kitchen created. It occurs intermittently, so we have had some kitchens converge successfully, and without any modifications to the kitchen file in either case. Do you have any insight on this? Any steps to troubleshoot further? We’re stumped on next steps on our end.

Yeah, we have already created that resource pool. I tried removing the parameter from the kitchen file just be sure we don’t have typos or some weird spacing issue. As you can see from the below console output, that resource pool definitely already exists and matches what we were specifying in our kitchen file. This is what is leading us to believe there could be a bug in the gem. Do you think this is the case? Should we be filing this as an issue on GitHub?

```````` Console Output ``````````

root@some_chefdk_docker:# kitchen create -l debug

-----> Starting Test Kitchen (v2.10.0)

$$$$$$ Deprecated configuration detected:

customize

Run 'kitchen doctor' for details.

D Berksfile found at /foo/bar/Berksfile, using Berkshelf to resolve cookbook dependencies

D Berkshelf 7.1.0 library loaded

-----> Creating <Kitchen-Kitchen>...

D Starting kitchen-vcenter 2.9.0

D Search of all resource pools found: ["Windows Kitchen Testing", "SOME_Tenant::domain-123::group-123", "SOME_Tenant::domain-1213::group-123", "SOME_Tenant::domain-123::datastore-123", "SOME_Tenant::domain-1011::datastore-123", "SOME_Tenant::domain-123::group-123", "SOME_Tenant-1::domain-789::group-123", "SOME_Tenant-1::domain-123::group-123", "SOME_Tenant-1::domain-456::group-123", "SOME_Tenant::domain-123::group-123", "SOME_Tenant::domain-123::group-123", "Kitchen Testing"]

See https://github.com/chef/customer-bugs/issues/409 for additional details

**Comment by tecracer-theinen** [comment]
Wow this is an old issue, sorry that it slipped past me.

Is it still valid? As I cannot see the customer-bugs repo, I am missing some info (the kitchen config or more specifically the requested resource pool).

My gut feeling says that the intermittent nature might be related to the order of returned responses.

**Comment by vkarve-chef** [comment]
sharing log snippet

```
root@redacted:~/dir# kitchen converge -l debug
-----> Starting Test Kitchen (v2.10.0)
$$$$$$ Deprecated configuration detected:
customize
Run 'kitchen doctor' for details.

D      Berksfile found at /root/dir/Berksfile, using Berkshelf to resolve cookbook dependencies
D      Berkshelf 7.1.0 library loaded
-----> Creating <Kitchen-Kitchen>...
D      Starting kitchen-vcenter 2.9.0
D      Search for resource pools found: ["Kitchen Testing"]
D      OS for VM not configured, got "Linux" from VMware
       Assigning network <redacted>...
       Using vDS 'vds_vmnet' for network connectivity...
       Cloning 'Linux/chef_templates/kitchen-image-rhel7' to create the VM...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [InvalidArgument: A specified parameter was not correct: spec.pool] on Kitchen-Kitchen
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running 'kitchen diagnose --all' for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [InvalidArgument: A specified parameter was not correct: spec.pool] on Kitchen-Kitchen
D      ----------------------
D      ------Backtrace-------
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:181:in 'report_errors'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:172:in 'run_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command/action.rb:35:in 'block in call'
D      /opt/chef-workstation/embedded/lib/ruby/2.7.0/benchmark.rb:293:in 'measure'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command/action.rb:33:in 'call'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/cli.rb:52:in 'perform'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/cli.rb:198:in 'block (2 levels) in <class:CLI>'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in 'run'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in 'invoke_command'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in 'dispatch'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in 'start'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/bin/kitchen:11:in 'block in <top (required)>'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/errors.rb:170:in 'with_friendly_errors'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/bin/kitchen:11:in '<top (required)>'
D      /opt/chef-workstation/bin/kitchen:355:in 'load'
D      /opt/chef-workstation/bin/kitchen:355:in '<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [InvalidArgument: A specified parameter was not correct: spec.pool] on Kitchen-Kitchen
D      ----------------------
D      ------Backtrace-------
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/rbvmomi-3.0.0/lib/rbvmomi/vim/Task.rb:14:in 'wait_for_completion'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/kitchen-vcenter-2.9.0/lib/support/clone_vm.rb:600:in 'clone'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/kitchen-vcenter-2.9.0/lib/kitchen/driver/vcenter.rb:182:in 'create'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:495:in 'public_send'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:495:in 'block in perform_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:563:in 'synchronize_or_call'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:524:in 'block in action'
D      /opt/chef-workstation/embedded/lib/ruby/2.7.0/benchmark.rb:293:in 'measure'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:523:in 'action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:495:in 'perform_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:404:in 'create_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:392:in 'block (2 levels) in transition_to'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/lifecycle_hooks.rb:47:in 'run_with_hooks'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:391:in 'block in transition_to'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:390:in 'each'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:390:in 'transition_to'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:139:in 'converge'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:195:in 'public_send'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:195:in 'run_action_in_thread'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:166:in 'block (2 levels) in run_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in 'block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [InvalidArgument: A specified parameter was not correct: spec.pool]
D      ----------------------
D      ------Backtrace-------
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/rbvmomi-3.0.0/lib/rbvmomi/vim/Task.rb:14:in 'wait_for_completion'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/kitchen-vcenter-2.9.0/lib/support/clone_vm.rb:600:in 'clone'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/kitchen-vcenter-2.9.0/lib/kitchen/driver/vcenter.rb:182:in 'create'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:495:in 'public_send'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:495:in 'block in perform_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:563:in 'synchronize_or_call'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:524:in 'block in action'
D      /opt/chef-workstation/embedded/lib/ruby/2.7.0/benchmark.rb:293:in 'measure'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:523:in 'action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:495:in 'perform_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:404:in 'create_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:392:in 'block (2 levels) in transition_to'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/lifecycle_hooks.rb:47:in 'run_with_hooks'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:391:in 'block in transition_to'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:390:in 'each'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:390:in 'transition_to'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:139:in 'converge'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:195:in 'public_send'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:195:in 'run_action_in_thread'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:166:in 'block (2 levels) in run_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in 'block in create_with_logging_context'
D      ----End Backtrace-----
```

**Comment by tecracer-theinen** [comment]
Thanks Vikram.

I think this is a common thing with kitchen-vcenter prior to 2.10.2. As the error message about `spec.pool" does not really relate to the resource pool specified. It also pops up if authentication/permission problems exist for example - which later lead to the value being empty or otherwise invalid.

If there's a possibility to recheck with the most recent driver version, that might give a better explanation of the actual error. Otherwise, it's really tough to check without access to the system.

**Comment by vkarve-chef** [comment]
Thanks for clarifying @tecracer-theinen 

I tried to reproduce this issue with `kitchen-vcenter (2.10.2)` unsuccessfully. I feel, specifying the resource pool and target host rather than not, would improve that chances of `kitchen create` running successfully.
