### ISSUE TITLE
HTTP error (302), Unable to find SOAP operation: :issue

### ISSUE THREAD

**Issue by marekmrowca** [chef/kitchen-vcenter#27]
### Versions:
Chef Development Kit Version: 2.5.3
chef-client version: 13.8.5
berks version: 6.3.1
kitchen version: 1.20.0
inspec version: 1.51.21
kitchen-vcenter: 1.2.1
savon: 2.12.0
Version of vCenter: 6.5

### Scenario:
Hi,
I don't know if this project is being still developed, but I am having the following problem.
I am getting 302 when trying "kitchen test default":
```
-----> Starting Kitchen (v1.20.0)
-----> Cleaning up any prior instances of <default-CM-TMPL-TF-W2012R2x64-Symantec>
-----> Destroying <default-CM-TMPL-TF-W2012R2x64-Symantec>...
       Finished destroying <default-CM-TMPL-TF-W2012R2x64-Symantec> (0m0.00s).
-----> Testing <default-CM-TMPL-TF-W2012R2x64-Symantec>
-----> Creating <default-CM-TMPL-TF-W2012R2x64-Symantec>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [HTTP error (302): <html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
To follow the redirects I set the following in /root/.chefdk/gem/ruby/2.4.0/gems/savon-2.12.0/lib/savon:
:follow_redirects            => true,

Now I am getting:

```
-----> Starting Kitchen (v1.20.0)
-----> Cleaning up any prior instances of <default-CM-TMPL-TF-W2012R2x64-Symantec>
-----> Destroying <default-CM-TMPL-TF-W2012R2x64-Symantec>...
       Finished destroying <default-CM-TMPL-TF-W2012R2x64-Symantec> (0m0.00s).
-----> Testing <default-CM-TMPL-TF-W2012R2x64-Symantec>
-----> Creating <default-CM-TMPL-TF-W2012R2x64-Symantec>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Unable to find SOAP operation: :issue
Operations provided by your service: []] on default-CM-TMPL-TF-W2012R2x64-Symantec
```
From the log:
```
E, [2018-10-30T15:39:26.432315 #17280] ERROR -- Kitchen: Message: Failed to complete #create action: [Unable to find SOAP operation: :issue
Operations provided by your service: []] on default-CM-TMPL-TF-W2012R2x64-Symantec
E, [2018-10-30T15:39:26.432325 #17280] ERROR -- Kitchen: ----------------------
E, [2018-10-30T15:39:26.432340 #17280] ERROR -- Kitchen: ------Backtrace-------
E, [2018-10-30T15:39:26.432351 #17280] ERROR -- Kitchen: /root/.chefdk/gem/ruby/2.4.0/gems/savon-2.12.0/lib/savon/operation.rb:23:in `ensure_exists!'
E, [2018-10-30T15:39:26.432361 #17280] ERROR -- Kitchen: /root/.chefdk/gem/ruby/2.4.0/gems/savon-2.12.0/lib/savon/operation.rb:15:in `create'
E, [2018-10-30T15:39:26.432371 #17280] ERROR -- Kitchen: /root/.chefdk/gem/ruby/2.4.0/gems/savon-2.12.0/lib/savon/client.rb:32:in `operation'
E, [2018-10-30T15:39:26.432381 #17280] ERROR -- Kitchen: /root/.chefdk/gem/ruby/2.4.0/gems/savon-2.12.0/lib/savon/client.rb:36:in `call'
E, [2018-10-30T15:39:26.432390 #17280] ERROR -- Kitchen: /root/.chefdk/gem/ruby/2.4.0/gems/kitchen-vcenter-1.2.1/lib/sso.rb:94:in `invoke'
E, [2018-10-30T15:39:26.432400 #17280] ERROR -- Kitchen: /root/.chefdk/gem/ruby/2.4.0/gems/kitchen-vcenter-1.2.1/lib/sso.rb:72:in `request_bearer_token'
E, [2018-10-30T15:39:26.432409 #17280] ERROR -- Kitchen: /root/.chefdk/gem/ruby/2.4.0/gems/kitchen-vcenter-1.2.1/lib/kitchen/driver/vcenter.rb:195:in `connect'
E, [2018-10-30T15:39:26.432419 #17280] ERROR -- Kitchen: /root/.chefdk/gem/ruby/2.4.0/gems/kitchen-vcenter-1.2.1/lib/kitchen/driver/vcenter.rb:60:in `create'
E, [2018-10-30T15:39:26.432429 #17280] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:469:in `public_send'
E, [2018-10-30T15:39:26.432438 #17280] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:469:in `block in perform_action'
E, [2018-10-30T15:39:26.432448 #17280] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:536:in `synchronize_or_call'
E, [2018-10-30T15:39:26.432457 #17280] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:498:in `block in action'
E, [2018-10-30T15:39:26.432467 #17280] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
...
```
Does anyone have a clue why this error occurs?

I can put .kitchen.yml here also if necessary.

**Comment by jjasghar** [comment]
@russellseymour ping :)

**Comment by tas50** [comment]
I'm going to close this out since we haven't heard back. If this is still an issue feel free to open it back up.
