### ISSUE TITLE
Error vAPI Unauthenticated

### ISSUE THREAD

**Issue by Inveracity** [chef/kitchen-vcenter#39]
### Versions:
* Version of kitchen-vcenter: 1.3.1
* Version of test-kitchen: 1.23.1
* Version of chef: 14.7.17

### Platform Details
* Version of vCenter: 6.5.0, 8024368
* Version of ESXi: 6.5.0, 7388607 

### Scenario:
Running kitchen test command against vCenter via alpine docker container.

### Steps to Reproduce:
```bash
bundle exec kitchen test -d always ubuntu-1604 --log-level=debug
```

### Expected Result:
Creates VM and and SSH's to the VM to run commands via CI

### Actual Result:
```
ERROR -- vAPI: VapiError (Com::Vmware::Vapi::Std::Errors::Unauthenticated)
```

### More details
The authentication against vcenter works in  `kitchen-vcenter (>= 1.2.1.3)` with `test-kitchen (> 1.2.0)` however that yields other problems with kitchen trying to randomly (sometimes it works sometimes it doesn't) SSH to an IP address that does not exist. I was hoping to fix that problem by upgrading everything but now run into this authentication problem instead.

### .kitchen.yml
```yaml
---
driver:
  name: vcenter
  vcenter_username: <%= ENV['VCENTER_USER'] %>
  vcenter_password: <%= ENV['VCENTER_PASSWORD'] %>
  vcenter_host: vcenter-01
  vcenter_disable_ssl_verify: true
  folder: development
  network: prod_network
  datastore: DataStore
  datacenter: DataCenter
  cluster: dc1
  memoryMB: 32768
  numCPUs: 16
  numCoresPerSocket: 16

transport:
  username: builduser
  ssh_key: test-extras/salt-test_rsa

provisioner:
  name: salt_solo
  formula: ./
  dependencies:
    - name: test-extras
      path: ./
  pillars_from_directories:
    - ../salt-pillars
  install_after_init_environment: true
  state_top_from_file: <%= ENV['HIGHSTATE'] || true %>
  salt_force_color: true
  require_chef: false
  salt_copy_filter:
    - .git
    - .kitchen

platforms:
  # Ubutnu 16.04
  - name: ubuntu-1604
    driver_config:
      template: templates/agent-ubuntu16.04
    provisioner:
      init_environment: |
        sudo systemctl stop salt-minion || true
        sleep 2
        sudo pkill salt-minion || true
      grains:
        katana_groups:
          - lin_general_slaves

verifier:
  name: inspec
  sudo: false

suites:
  -
    name: default
<% if File.file?("top.kitchen") and (ENV['HIGHSTATE'] || 'true') == 'false' %>
<%= File.read("top.kitchen") %>
<% end %>
```

### Full output

```
$ bundle exec kitchen diagnose ubuntu-1604
---
timestamp: 2018-11-22 12:30:18 UTC
kitchen_version: 1.23.2
instances:
  default-ubuntu-1604:
    platform:
      os_type: unix
      shell_type: bourne
    state_file: {}
    driver:
      clone_type: :full
      cluster: dc1
      datacenter: DataCenter
      datastore: DataStore
      folder: development
      kitchen_root: "/builds/salt-states"
      log_level: :info
      memoryMB: 32768
      name: vcenter
      network: prod_agents
      numCPUs: 16
      numCoresPerSocket: 16
      poweron: true
      pre_create_command: 
      resource_pool: 
      targethost: 
      template: templates/agent-ubuntu16.04-datacore3
      test_base_path: "/builds/salt-states/test/integration"
      vcenter_disable_ssl_verify: true
      vcenter_host: vcenter-01
      vcenter_password: <snip>
      vcenter_username: <snip>
      vm_name: 
    provisioner:
      bootstrap_url: https://raw.githubusercontent.com/saltstack/kitchen-salt/master/assets/install.sh
      cache_commands: []
      chef_bootstrap_url: https://www.chef.io/chef/install.sh
      command_prefix: 
      debug: 
      dependencies:
      - name: test-extras
        path: "./"
      downloads: {}
      dry_run: false
      formula: "./"
      ftp_proxy: 
      gpg_home: "~/.gnupg/"
      gpg_key: 
      grains:
        katana_groups:
        - lin_general_slaves
      http_proxy: 
      https_proxy: 
      init_environment: |
        sudo systemctl stop salt-minion || true
        sleep 2
        sudo pkill salt-minion || true
      install_after_init_environment: true
      is_file_root: false
      kitchen_root: "/builds/salt-states"
      local_salt_root: 
      max_retries: 1
      name: salt_solo
      omnibus_cachier: false
      pillars_from_directories:
      - "../salt-pillars"
      pip_bin: pip
      pip_editable: false
      pip_extra_index_url: []
      pip_index_url: https://pypi.python.org/simple/
      pip_pkg: salt==%s
      remote_states: 
      require_chef: false
      retry_on_exit_code: []
      root_path: "/tmp/kitchen"
      salt_apt_repo: https://repo.saltstack.com/apt/ubuntu/16.04/amd64/
      salt_apt_repo_key: https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub
      salt_bootstrap_options: ''
      salt_bootstrap_url: https://bootstrap.saltstack.com
      salt_config: "/etc/salt"
      salt_copy_filter:
      - ".git"
      - ".kitchen"
      salt_env: base
      salt_file_root: "/srv/salt"
      salt_force_color: true
      salt_install: bootstrap
      salt_minion_config: "/etc/salt/minion"
      salt_minion_config_dropin_files: []
      salt_minion_config_template: 
      salt_minion_extra_config: {}
      salt_minion_id: 
      salt_pillar_root: "/srv/pillar"
      salt_ppa: ppa:saltstack/salt
      salt_spm_root: "/srv/spm"
      salt_state_top: "/srv/salt/top.sls"
      salt_version: latest
      salt_yum_repo: https://repo.saltstack.com/yum/redhat/$releasever/$basearch/archive/%s
      salt_yum_repo_key: https://repo.saltstack.com/yum/redhat/$releasever/$basearch/archive/%s/SALTSTACK-GPG-KEY.pub
      salt_yum_repo_latest: https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm
      salt_yum_rpm_key: https://repo.saltstack.com/yum/redhat/7/x86_64/archive/%s/SALTSTACK-GPG-KEY.pub
      state_collection: false
      state_top: {}
      state_top_from_file: true
      sudo: true
      sudo_command: sudo -E
      test_base_path: "/builds/salt-states/test/integration"
      vendor_path: 
      vendor_repo: {}
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/builds/salt-states"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway: 
      ssh_gateway_port: 22
      ssh_gateway_username: 
      ssh_http_proxy: 
      ssh_http_proxy_password: 
      ssh_http_proxy_port: 
      ssh_http_proxy_user: 
      ssh_key: "/builds/salt-states/test-extras/salt-test_rsa"
      test_base_path: "/builds/salt-states/test/integration"
      username: builduser
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix: 
      debug: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      inspec_tests: []
      kitchen_root: "/builds/salt-states"
      log_level: :info
      name: inspec
      root_path: "/tmp/verifier"
      sudo: false
      sudo_command: sudo -E
      suite_name: default
      test_base_path: "/builds/salt-states/test/integration"
$ bundle exec kitchen test -d always ubuntu-1604 --log-level=debug
-----> Starting Kitchen (v1.23.2)
D      winrm requested, loading winrm gem (["~> 2.0"])
D      winrm is loaded.
D      winrm-fs requested, loading winrm-fs gem (["~> 1.0"])
D      winrm-fs is loaded.
D      winrm-elevated requested, loading winrm-elevated gem (["~> 1.0"])
D      winrm-elevated is loaded.
-----> Cleaning up any prior instances of <default-ubuntu-1604>
-----> Destroying <default-ubuntu-1604>...
       Finished destroying <default-ubuntu-1604> (0m0.00s).
-----> Testing <default-ubuntu-1604>
-----> Creating <default-ubuntu-1604>...
E, [2018-11-22T12:30:24.384377 #24] ERROR -- vAPI: VapiError (Com::Vmware::Vapi::Std::Errors::Unauthenticated)

-----> Destroying <default-ubuntu-1604>...
       Finished destroying <default-ubuntu-1604> (0m0.00s).
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [VapiError] on default-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [VapiError] on default-ubuntu-1604
D      ----------------------
D      ------Backtrace-------
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:183:in `report_errors'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:174:in `run_action'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/command/test.rb:42:in `block in call'
D      /usr/local/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/command/test.rb:38:in `call'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/cli.rb:52:in `perform'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/cli.rb:245:in `test'
D      /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
D      /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
D      /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
D      /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/bin/kitchen:13:in `block in <top (required)>'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/bin/kitchen:13:in `<top (required)>'
D      /usr/local/bundle/bin/kitchen:23:in `load'
D      /usr/local/bundle/bin/kitchen:23:in `<top (required)>'
D      /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
D      /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
D      /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
D      /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
D      /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
D      /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
D      /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
D      /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
D      /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
D      /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
D      /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
D      /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
D      /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
D      /usr/local/bundle/bin/bundle:23:in `load'
D      /usr/local/bundle/bin/bundle:23:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [VapiError] on default-ubuntu-1604
D      ----------------------
D      ------Backtrace-------
D      /usr/local/bundle/gems/vsphere-automation-sdk-6.6.1/client/sdk/runtime/lib/vapi/bindings/service.rb:69:in `invoke_with_info'
D      /usr/local/bundle/gems/vsphere-automation-sdk-6.6.1/client/sdk/com/vmware/cis.rb:141:in `create'
D      /usr/local/bundle/gems/kitchen-vcenter-1.3.1/lib/kitchen/driver/vcenter.rb:241:in `connect'
D      /usr/local/bundle/gems/kitchen-vcenter-1.3.1/lib/kitchen/driver/vcenter.rb:62:in `create'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `public_send'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `block in perform_action'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:551:in `synchronize_or_call'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:513:in `block in action'
D      /usr/local/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:512:in `action'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `perform_action'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:394:in `create_action'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:162:in `verify'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:191:in `block in test'
D      /usr/local/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:187:in `test'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      /usr/local/bundle/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [VapiError]
D      ----------------------
D      ------Backtrace-------
D      /usr/local/bundle/gems/vsphere-automation-sdk-6.6.1/client/sdk/runtime/lib/vapi/bindings/service.rb:69:in `invoke_with_info'
D      /usr/local/bundle/gems/vsphere-automation-sdk-6.6.1/client/sdk/com/vmware/cis.rb:141:in `create'
D      /usr/local/bundle/gems/kitchen-vcenter-1.3.1/lib/kitchen/driver/vcenter.rb:241:in `connect'
D      /usr/local/bundle/gems/kitchen-vcenter-1.3.1/lib/kitchen/driver/vcenter.rb:62:in `create'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `public_send'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `block in perform_action'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:551:in `synchronize_or_call'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:513:in `block in action'
D      /usr/local/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:512:in `action'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `perform_action'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:394:in `create_action'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:162:in `verify'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:191:in `block in test'
D      /usr/local/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:187:in `test'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /usr/local/bundle/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      /usr/local/bundle/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
```

### Dockerfile

```
FROM ruby:2.5.3-alpine3.8
RUN apk add --update git \
                     openssh \
                     build-base \
                     libxml2-dev \
                     libxslt-dev \
                     && rm -rf /var/cache/apk/*

RUN gem install bundler
COPY Gemfile Gemfile
RUN bundler install --full-index
```

### Final thoughts
I made sure to read the documentation on how to set up the kitchen.yml again after updating everything, and I can't seem to find any new or different settings, so now I don't know what to do, and help is appreciated!

**Comment by Inveracity** [comment]
I see #26 might be related to this, so I'll close this for now.
