### ISSUE TITLE
On Windows 10 - Fails to find "libcurl" when running test kitchen

### ISSUE THREAD

**Issue by jasonnalewak** [chef/kitchen-vcenter#68]
### Versions:
* Version of kitchen-vcenter: 2.2.2
* Version of test-kitchen: 1.24.0
* Version of chef: 14.10.9
* Version of ruby: 2.5.0
* Version of chef-workstation: 0.2.48

### Platform Details
* Version of vCenter: none (reproduced gem error just trying to run kitchen list)
* Version of ESXi: none

### Scenario:
A customer reached out and notified me they cannot use the kitchen-vcenter driver for their local dev needs.  I don't have a vcenter instance to test against but reproduced the error just by trying to execute Test Kitchen using the kitchen-vcenter driver on an AWS workspace instance of Windows 10 and an example kitchen.yml configured for vcenter.

### Steps to Reproduce:
1.  Log into a fresh Windows 10 instance.
2.  Installed choco
3.  Used choco to install chef-workstation
4.  Used 'chef gem install kitchen-vcenter'
5.  Generated a simple Chef cookbook and edited the kitchen.yml for vcenter
6.  Ran 'kitchen list' and received the error below.

### Expected Result:
An error stating that the vcenter host could not be found.

### Actual Result:
```PS D:\Users\jnalewak\chef-repo\cookbooks\my_etc_hosts> kitchen list -l debug
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'vcenter' driver from the load path.Could not open library 'libcurl': The specified module could not be found.
.
Could not open library 'libcurl.dll': The specified module could not be found.
.
Could not open library 'libcurl.so.4': The specified module could not be found.
.
Could not open library 'libcurl.so.4.dll': The specified module could not be found.

>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ClientError
D      Message: Could not load the 'vcenter' driver from the load path.Could not open library 'libcurl': The specified module could not be found.
.
Could not open library 'libcurl.dll': The specified module could not be found.
.
Could not open library 'libcurl.so.4': The specified module could not be found.
.
Could not open library 'libcurl.so.4.dll': The specified module could not be found.

D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/plugin.rb:56:in `rescue in load'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/plugin.rb:34:in `load'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/driver.rb:38:in `for_plugin'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:234:in `new_driver'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:247:in `new_instance'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:142:in `block in build_instances'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:141:in `map'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:141:in `with_index'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:141:in `build_instances'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:117:in `instances'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:112:in `filtered_instances'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:142:in `parse_subcommand'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command/list.rb:30:in `call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/cli.rb:52:in `perform'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/cli.rb:120:in `list'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/bin/kitchen:13:in `block in <top (required)>'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/bin/kitchen:13:in `<top (required)>'
D      C:/opscode/chef-workstation/bin/kitchen:322:in `load'
D      C:/opscode/chef-workstation/bin/kitchen:322:in `<main>'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: LoadError
D      Message: Could not open library 'libcurl': The specified module could not be found.
.
Could not open library 'libcurl.dll': The specified module could not be found.
.
Could not open library 'libcurl.so.4': The specified module could not be found.
.
Could not open library 'libcurl.so.4.dll': The specified module could not be found.

D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/plugin.rb:56:in `rescue in load'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/plugin.rb:34:in `load'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/driver.rb:38:in `for_plugin'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:234:in `new_driver'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:247:in `new_instance'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:142:in `block in build_instances'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:141:in `map'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:141:in `with_index'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:141:in `build_instances'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/config.rb:117:in `instances'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:112:in `filtered_instances'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:142:in `parse_subcommand'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command/list.rb:30:in `call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/cli.rb:52:in `perform'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/cli.rb:120:in `list'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/bin/kitchen:13:in `block in <top (required)>'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/bin/kitchen:13:in `<top (required)>'
D      C:/opscode/chef-workstation/bin/kitchen:322:in `load'
D      C:/opscode/chef-workstation/bin/kitchen:322:in `<main>'
D      ----End Backtrace-----```

Kitchen Path: C:/opscode/chef-workstation/bin\kitchen.bat
Chef Path: C:/opscode/chef-workstation/bin\chef.bat

**Comment by tas50** [comment]
This is a known issue that we're hitting due to the ethon gem which is a dep of a dep of a dep. It's not finding the curl dep. I'm working on it at the moment.

**Comment by jasonnalewak** [comment]
Thanks and sorry I didn't realize there had been an issue opened in the chef-dk repo for this exact failure.  https://github.com/chef/chef-dk/issues/2025

**Comment by Monstros** [comment]
For those that are looking for a work around I followed the steps here:
* [jekyll dependency error](https://stackoverflow.com/questions/47720302/jekyll-serve-dependency-error-could-not-open-lib-curl/47754520#47754520)

Basically get a copy of the `libcurl.dll` (the one in the link used was `7.4.0`) and copy it to `C:\opscode\chefdk\bin`. Once done try running test kitchen with the driver and it should allow you to proceed forward.

**Comment by tzvifriedman** [comment]
I can't get this workaround to work for Windows. Not sure if I have a wrong version of libcurl or something. Any other workarounds I can try or troubleshooting steps to get the above fix to work?

**Comment by smoothdude11** [comment]
> I can't get this workaround to work for Windows. Not sure if I have a wrong version of libcurl or something. Any other workarounds I can try or troubleshooting steps to get the above fix to work?

I moved the file into C:\opscode\chefdk\embedded\bin, and that worked for kitchen.

**Comment by jasonnalewak** [comment]
@smoothdude11  which version of the libcurl dll did you end up placing in the C:\opscode\chefdk\embedded\bin directory?

**Comment by Monstros** [comment]
The version that worked for me is the one in the link which is `7.4.0`. Also, sorry about getting the pathing mixed up, the path @smoothdude11 posted sounds correct.

**Comment by cattywampus** [comment]
@jasonnalewak were you able to get the work around to work for you? I tried copying several variants of the DLL into that exact path (I think...it's been a while) with no luck. I think I did however have better luck if I used the git bash shell, because that ships with curl and has it in a place where kitchen can find it. Using ChefDK Powershell never worked for me.

**Comment by jasonnalewak** [comment]
It didn't work for me either Keith.

**Comment by tas50** [comment]
This has been fixed now that the vmware SDK no longer requires the ethon gem!
